## NumPy Basics 

In [ ]:
# Written by Tyler Beetle for Python for Data Science and Machine Learning Bootcamp Udemy Course.

In [6]:
import numpy as np

In [3]:
list = [1,2,3]

In [8]:
np.array(list)

array([1, 2, 3])

In [9]:
arr = np.array(list)

In [10]:
arr

array([1, 2, 3])

In [15]:
list_lists = [[1,2,3],[4,5,6],[7,8,9,]]

In [16]:
list_lists

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
arr2 = np.array(list_lists)

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
np.arange(0,9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
np.arange(0,9,3)

array([0, 3, 6])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [29]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.linspace(0,9,4)

array([0., 3., 6., 9.])

In [34]:
np.random.rand(5)

array([0.96659136, 0.9502101 , 0.54753906, 0.55859631, 0.93730529])

In [35]:
np.random.rand(5,5)

array([[0.90390405, 0.1565473 , 0.40260695, 0.9428075 , 0.16571133],
       [0.0925674 , 0.55948631, 0.87916837, 0.8279802 , 0.87983893],
       [0.89990729, 0.77826913, 0.9398085 , 0.74463557, 0.39443687],
       [0.62800806, 0.09200867, 0.36739181, 0.809755  , 0.28374812],
       [0.06797603, 0.04337351, 0.77798737, 0.05412586, 0.14294626]])

In [36]:
np.random.randn(4,4)

array([[-1.49476699,  2.09970125,  0.98043565, -0.80658668],
       [-0.97656912,  0.15419749, -0.0339888 , -0.48194858],
       [ 0.86947565,  2.70291648, -1.05380493, -0.78189718],
       [ 1.44079619, -0.7622005 , -0.69278378, -0.09928506]])

In [39]:
np.random.randint(1,100,25)

array([88, 92, 80, 24, 60, 70, 54, 39, 46, 57, 73, 15, 21, 94, 79, 76, 94,
       65, 39, 62, 95, 40, 29, 43, 70])

In [40]:
arr = np.arange(10)

In [41]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
random_arr = np.random.randint(0,50,10)

In [43]:
random_arr

array([19, 22, 42,  5, 16, 20, 46, 41, 30, 39])

In [45]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
random_arr.max()

46

In [47]:
random_arr.min()

5

In [48]:
random_arr.argmax()

6

In [49]:
random_arr.argmin()

3

In [51]:
arr = arr.reshape(5,2)

In [52]:
arr.shape

(5, 2)

In [53]:
arr.dtype

dtype('int64')

In [54]:
from numpy.random import randint

In [55]:
randint(2,10)

6

## Indexing Practice

In [56]:
arr = np.arange(0,11)

In [57]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
arr[0]

0

In [59]:
arr[8]

8

In [60]:
arr[4:7]

array([4, 5, 6])

In [61]:
arr[:3]

array([0, 1, 2])

In [62]:
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr[0:3] = 100

In [64]:
arr

array([100, 100, 100,   3,   4,   5,   6,   7,   8,   9,  10])

In [65]:
arr = np.arange(0,11)

In [66]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
slice = arr[0:5]

In [68]:
slice[:] = 1001

In [69]:
slice

array([1001, 1001, 1001, 1001, 1001])

In [70]:
arr

array([1001, 1001, 1001, 1001, 1001,    5,    6,    7,    8,    9,   10])

In [71]:
copy = arr.copy()

In [72]:
copy

array([1001, 1001, 1001, 1001, 1001,    5,    6,    7,    8,    9,   10])

In [73]:
arr

array([1001, 1001, 1001, 1001, 1001,    5,    6,    7,    8,    9,   10])

In [74]:
copy[:] = 100

In [75]:
copy 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [90]:
arr_2d = np.array([[5,3,4],[9,4,8],[4,3,2]])

In [91]:
arr_2d

array([[5, 3, 4],
       [9, 4, 8],
       [4, 3, 2]])

In [92]:
arr_2d[0][0]

5

In [109]:
arr_2d[2:,1:]

array([[3, 2]])

In [110]:
arr

array([1001, 1001, 1001, 1001, 1001,    5,    6,    7,    8,    9,   10])

In [111]:
arr = np.arange(1,11)

In [114]:
bool_arr = arr > 5

In [115]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [116]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [117]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [118]:
arr[arr<3]

array([1, 2])

## NumPy Operations

In [4]:
arr = np.arange(0,11)

In [5]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [6]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [8]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [11]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [12]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [13]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [15]:
arr.max()

10

In [16]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [31]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [34]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [40]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
np.random.uniform(0,1)

0.9247275829765029

In [44]:
np.random.normal(0,1,25)

array([ 0.59466148, -0.06326608,  0.79323226, -0.00509779,  0.84123773,
        0.08237951, -1.34391628,  0.80623552,  1.46290904,  1.72043192,
        0.51987448, -0.32796583,  0.52672411,  1.02589194, -0.9952541 ,
        0.90348822,  0.76631432,  0.88373345, -0.75301433, -2.10885936,
        0.28194178, -0.83278068, -0.34487804,  0.10906919, -0.99810508])

In [51]:
np.arange(0.01,1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [52]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [53]:
mat = np.arange(1,26).reshape(5,5)

In [54]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [66]:
mat[3,4]

20

In [79]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [74]:
mat[3:,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
mat.sum()

325

In [76]:
mat.std()

7.211102550927978

In [77]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])